# Runs a powerdns authoritative server 

version: '3.3'

services:
  mysql:
    environment: 
      MYSQL_DATABASE: powerdns
      MYSQL_ROOT_PASSWORD: powerdns
    image: mariadb
    restart: always
    volumes:
     - ./mariadb:/var/lib/mysql

  powerdns:
    image: pschiffe/pdns-mysql
    ports:
      - "8081:8081"
      # Uncomment below to forward to your machine (you will likely have to disable whatever DNS is running)
      # - "53:53/tcp"
      # - "53:53/udp"
    environment: 
       PDNS_webserver_allow_from: "0.0.0.0/0,::/0"
       PDNS_gmysql_password: "powerdns"
       PDNS_webserver_address: "0.0.0.0"
       PDNS_api_key: "secret" 
       PDNS_api: "yes" 
